#[derive(Deserialize, Serialize, Debug, Default, Clone)]
pub struct CSVStruct {
    // weapon values
    pub macro_name: String,
    pub class: String,
    pub alias: String,
    pub component: String,
    pub id_name: String,
    pub id_basename: String,
    pub id_shortname: String,
    pub makerrace: String,
    pub description: String,
    pub mk: String,
    pub bullets_used: String,
    pub wreload_rate: String,
    pub wreload_time: String,
    pub rot_speed_max: String,
    pub rot_accel_max: String,
    pub hull_max: String,
    pub hull_threshold: String,
    pub hull_integrated: String,
    pub hull_hittable: String,
    pub heat_overheat: String,
    pub heat_cooldelay: String,
    pub heat_coolrate: String,
    pub heat_reenable: String,
    pub firing_start_fx: String,
    pub firing_stop_fx: String,
    // bullet values
    pub bullet_macro_name: String,
    pub bullet_class: String,
    pub bullet_component: String,
    pub ammo_value: String,
    pub ammo_reload: String,
    pub bullet_speed: String,
    pub bullet_lifetime: String,
    pub bullet_amount: String,
    pub bullet_barrelamount: String,
    pub bullet_icon: String,
    pub bullet_timediff: String,
    pub bullet_angle: String,
    pub bullet_maxhits: String,
    pub bullet_ricochet: String,
    pub bullet_scale: String,
    pub bullet_attach: String,
    pub bullet_range: String,
    pub bullet_restitution: String,
    pub bullet_selfdestruct: String,
    pub bullet_delay: String,
    pub heat_value: String,
    pub heat_initial: String,
    pub reload_rate: String,
    pub reload_time: String,
    pub damage_value: String,
    pub damage_shield: String,
    pub damage_repair: String,
    pub damage_min: String,
    pub damage_max: String,
    pub damage_time: String,
    pub damage_hull: String,
    pub impact: String,
    pub launch: String,
    pub weapon_system: String,
    pub area_damage: String,
    pub sound_ambient: String,
    // ware values
    pub ware_id: String,
    pub ware_name: String,
    pub ware_desc: String,
    pub ware_group: String,
    pub ware_transport: String,
    pub ware_volume: String,
    pub ware_tags: String,
    pub ware_price_min: String,
    pub ware_price_avg: String,
    pub ware_price_max: String,
    pub ware_production: String,
    // pub ware_prod_time: String,
    // pub ware_prod_amount: String,
    // pub ware_prod_method: String,
    // pub ware_prod_name: String,
    // pub ware_prod_wares: String,
    // pub ware_prod_amts: String,
    pub ware_comp_ref: String,
    pub ware_comp_amt: String,
    pub ware_license: String,
    pub ware_use_threshold: String,
    pub ware_owners: String,
}
